### ISSUE TITLE
"Exclude path not found" in Windows

### ISSUE THREAD

**Issue by mousavian** [slampenny/Swaggervel#23]
Hi,
There is an "excludes" section in the config file ([app.php](https://github.com/slampenny/Swaggervel/blob/master/src/config/app.php#L36)) that contains absolute path of directories to exclude, while swagger-php itself will convert paths to the canonicalized absolute paths ( [See here] (https://github.com/zircote/swagger-php/blob/22cbbf28a681cbb0ad0118f64b24edb57a4c1ed9/library/Swagger/Swagger.php#L237) ). 

I'm raising this issue because at the end, we need to [implode them](https://github.com/slampenny/Swaggervel/blob/master/src/Jlapp/Swaggervel/routes.php#L51) using colon delimiter which is causing error in windows.
 
**Command:**
>php C:\wamp\www\p1/vendor/zircote/swagger-php/swagger.phar C:\wamp\www\p1/app/controllers/api -o C:\wamp\www\p1\app/storage/docs   --default-swagger-version '1.2'   -e C:\wamp\www\p1\app/storage:C:\wamp\www\p1\app/tests:C:\wamp\www\p1\app/views

**Result:**
>Swagger-PHP 0.9.6
>-----------------
>[INFO] Exclude path: "C:\wamp\www\p1\public\C" not found
>[INFO] Exclude path: "C:\wamp\www\p1\public\C" not found
>[INFO] Exclude path: "C:\wamp\www\p1\public\C" not found
>Created C:\wamp\www\p1\app/storage/docs\api-docs.json
>Created C:\wamp\www\p1\app/storage/docs\index.php
>Created C:\wamp\www\p1\app/storage/docs\/pets.json

**Comment by slampenny** [comment]
I switched to using the actual Swagger php class to do this instead of the command line. Please give it a shot and see if that solves your problem. It works on my system.
