### ISSUE TITLE
Compatibility with Laravel 5

### ISSUE THREAD

**Issue by Ynk33** [slampenny/Swaggervel#26]
Hello,
It seems that Swaggervel is not compatible with Laravel 5. Whenever I try the command "php artisan swaggervel:install", I get a BadMethodCallException with message 'Call to undefined method [package]'.

Is it possible to update Swaggervel to make it compatible with Laravel 5 please ?

Thanks for your help

**Comment by slampenny** [comment]
There is a fork which is compatible with laravel 5, but I don't have a pull request from it. I'll try to do this soon, but in the meantime take a look through the forks.

**Comment by luoshiben** [comment]
Thanks for the great package. I'd also love to see Swaggervel updated to support Laravel 5. Cheers!

**Comment by DarkaOnLine** [comment]
Hi, @slampenny 

I was unable to wait for your L5 version so I made one. [L5-Swagger](https://github.com/DarkaOnLine/L5-Swagger) based on your code.

If this approach is good for you I can make a pull request

**Comment by FoxxMD** [comment]
Thanks @DarkaOnLine :+1:

**Comment by slampenny** [comment]
Thanks @DarkaOnLine , but since you didn't do a pull request, I had to do it myself.  Laravel 5 is now supported on Master, or the 2.0 branch, which is stable.

**Comment by FoxxMD** [comment]
great news @slampenny! Thanks.
