### ISSUE TITLE
Incompatibility with Dingo API

### ISSUE THREAD

**Issue by sblawrie** [slampenny/Swaggervel#30]
At the bottom of my `providers` array I have:

```php
        'Dingo\Api\Provider\ApiServiceProvider',
        'Jlapp\Swaggervel\SwaggervelServiceProvider',
```

I get a `Call to undefined method Illuminate\Routing\Router::api()` error when I try to load a page.  If I delete the Swaggervel provider, the error goes away.

**Comment by tosh001** [comment]
I am getting the same issue here, any udpates on this?

**Comment by breekachu** [comment]
Same issue for me as well. When will this be fixed?

**Comment by slampenny** [comment]
I don't actually know what the Dingo API is... Swaggervel doesn't call that method. If one of you guys want to take a look at it, I'd be grateful. Otherwise I'll have to look at it when I have a spare moment.

**Comment by slampenny** [comment]
You know, I took a quick look at this (and even tried to fix it). Dingo uses non-standard routing, whereas Swaggervel uses the technique suggested in the Laravel docs. This seems like Dingo's issue, not mine.

If anyone figures out a solution, submit a pull request and I'll merge it.
