### ISSUE TITLE
Swagger 2.0

### ISSUE THREAD

**Issue by lukepolo** [slampenny/Swaggervel#33]
Thoughts about upgrading to the new UI / dev branch of php swagger?

https://github.com/zircote/swagger-php/tree/2.x

**Comment by slampenny** [comment]
@lukepolo I'll look into this, thanks!

**Comment by dmyers** [comment]
:+1:

**Comment by dmyers** [comment]
:+1: 

The 2.0 branch has been released to master.

**Comment by vscuorzo** [comment]
Any update on progress for Swagger 2.0 support? I'm looking to use this on a Laravel project at work and would like to implement Swagger 2.0 annotations.

**Comment by dmyers** [comment]
It has been released... this can be closed.

**Comment by dmyers** [comment]
@vscuorzo Until it is supported, you can also directly use swagger-php in your project using composer.
