### ISSUE TITLE
Class 'Route' not found when trying to publish with artisan

### ISSUE THREAD

**Issue by tzfrs** [slampenny/Swaggervel#37]
Hi,

I'm using Lumen and wanted to add Swaggervel to the application. If this doesn't work, just tell me. If it should work, here is what my problem is.

I added swaggervel to my dependencies

`"jlapp/swaggervel" : "2.0.*@dev"`

As you can see, the files are in my vendor folder

![image](https://cloud.githubusercontent.com/assets/3509557/7908026/cb9008d0-0840-11e5-80cf-e46d32eb4fa8.png)

In Lumen you add Service Providers in the `/PROJECTDIR/bootstrap/app.php` instead of in the `app/config/app.php`
Now, I wanted to run  `php artisan vendor:publish`. When I do this I'm getting the following message:

`Class 'Route' not found in /PROJECTDIR/vendor/jlapp/swaggervel/src/Jlapp/Swaggervel/routes.php on line 5`

Complete stacktrace

    PHP Stack trace:
    PHP   1. {main}() /PROJECTDIR/artisan:0
    PHP   2. require() /PROJECTDIR/artisan:18
    PHP   3. Laravel\Lumen\Application->register()     /PROJECTDIR/bootstrap/app.php:81
    PHP   4. Jlapp\Swaggervel\SwaggervelServiceProvider->register()     /PROJECTDIR/vendor/laravel/lumen-framework/src/Application.php:229
    PHP   5. require_once() /PROJECTDIR/vendor/jlapp/swaggervel/src/Jlapp/Swaggervel/SwaggervelServiceProvider.php:46`

Any idea why this doesn't work or what I did wrong?

**Comment by slampenny** [comment]
Have you tried adding Swaggervel after all your other providers?

Otherwise, try adding "use Illuminate\Support\Facades\Route; " to the routes.php file in the swaggervel directory. If that works, I'll add it to the branch.

**Comment by mpetrunic** [comment]
As far as i know this won't work in lumen because lumen uses different route library than laravel and therefore routing wont work. I suggest making separate branch for lumen with lumen routing library.

**Comment by slampenny** [comment]
Yeah, @tzfrs, if that's the case and Lumen uses a different route library, feel free to branch or fork this project and rewrite just the routing section for that platform.
