### ISSUE TITLE
No response in swagger-ui after fetching for a URL

### ISSUE THREAD

**Issue by BlazeNikhilesh** [slampenny/Swaggervel#38]
When I try to fetch the response for a particular URL, the swagger-ui shows nothing. When I see in networks, there is a request for that api and response is OK. Although, there is nothing on the screen. When I check console log, I see this error: 

"This API is using a deprecated version of Swagger!  Please see http://github.com/wordnik/swagger-core/wiki for more info"

What exactly am I missing out on it??

**Comment by slampenny** [comment]
which branch are you on? This hasn't happened to me.

Usually, if you get no response, it's because the default-base-path value in your config is wrong. A common problem is that your browser is at an http address, but default-base-path is at https, or you have a group route like api/v1, but have forgotten to add that to your default-base-path.

Let me know what you discover.

**Comment by BlazeNikhilesh** [comment]
I am on Master branch. Using Laravel 5. 
'default-base-path' => null, 
'default-api-version' => null,
'url' => null,

What am I missing on??

**Comment by slampenny** [comment]
try setting default-base-path to the route where your api calls lie. For instance, http://api.example.com/api/v1" if you're targeting "http://api.example.com/api/v1/test".  In the swagger code in your controller you'd set the path to be "test".

**Comment by BlazeNikhilesh** [comment]
And also, I haven't made any controllers for swagger yet. Is that a problem too? I am not aware of how that is done

**Comment by slampenny** [comment]
This package is just a Laravel friendly wrapper for other swagger packages. Questions about how to use swagger are out of scope.

I can however try and point you in the right direction: you don't make controllers specifically for swagger, you add swagger-formatted comments to your controllers. Here are some examples: https://github.com/zircote/swagger-php/tree/master/Examples
