### ISSUE TITLE
Composer Install Issues

### ISSUE THREAD

**Issue by andrewjwolf** [slampenny/Swaggervel#41]
slampenny/swaggervel could not be found in any version

composer require jlapp/swaggervel tried
Also tried :
	"require-dev": {
        "slampenny/Swaggervel": "~2.0@dev"
	},
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/slampenny/Swaggervel"
        }
    ],

Same issue

**Comment by slampenny** [comment]
"jlapp/swaggervel": "2.0.*@dev" You're missing the *

**Comment by slampenny** [comment]
also, why are you referencing the repo directly if you're using composer install????

**Comment by andrewjwolf** [comment]
note:"Also tried" - These were two different examples.
In my case the directions included did not work. I'd like to see these instructions included within the readme.md - I was able to resolve the issue with the above.
