### ISSUE TITLE
Swaggervel defaulting to Swagger-php 2.x

### ISSUE THREAD

**Issue by direwolf2494** [slampenny/Swaggervel#45]
After running composer update on my project. I'm now getting errors saying the annotations are deprecated. After some digging I found out that zircote/swagger-php master branch (which I assume swaggervel uses) is now using an update annotation system. To utilize the annotations older annotations you're required to use branch 1.x. I'd prefer not to rewrite all my swagger documentation.

**Comment by slampenny** [comment]
The master branch is for testing new features. Please use the 2.0 branch instead.
