### ISSUE TITLE
How to use YAML files

### ISSUE THREAD

**Issue by elothen** [slampenny/Swaggervel#47]
I've got this package working great with the doc blocks but I'd like to move my documentation out of my controllers into associated .yaml files.  I believe this is supported by Swagger 2.0, is there a way to make the swagervel scan pick them up?

**Comment by slampenny** [comment]
The mighty @tralves did the Swagger 2.0 code. Tiago?

**Comment by tralves** [comment]
Hi! I don't think you can use both yaml and swagger-php annotations. If you want just to export your current swagger-php documentation to yaml, you can:
- get the .json documentation in the ``/docs`` endpoint;
- go to http://editor.swagger.io/#/, File > Paste Json, and paste the json;

It converts automatically to yaml. I also use this editor to debug the documentation. It provides much better feedback than swagger-ui.

**Comment by elothen** [comment]
Thanks for the rapid responses!

I think I mis-stated what I'm looking for.  So currently with swagervel if you annotate your .php files they will be scanned and the api-docs.json file is created from the annotations in them.

I'm wondering if there's a way to use a side by side .yaml file and have that scanned instead of annotating the .php files directly and have swagervel automatically create the file needed by swagger-ui?

* MyController.php
* MyController.yaml

note: I just started trying to do all of this yesterday so I could be way wrong on some of this conceptually.  Thanks!

**Comment by tralves** [comment]
Hi,
I don't think that's possible, sorry. Swagger-ui doesn't support yaml yet (see https://github.com/swagger-api/swagger-ui/issues/595). Also, swagger-php doesn't generate .yaml files.

I understand why you don't want to use the php annotations in swagger-php. They are ugly, not very intuitive and hard to debug. The advantage is that you write them *with* php the code. The documentation is not updated. I use the examples in the swagger-php package and decided to stick with it after all...

If you don't want to use annotations (swagger-php), then maybe you don't need swaggervel. Just install the tools (swagger-editor, swagger-ui, ...) and create the documentation elsewhere.

**Comment by elothen** [comment]
Thank you both, that's exactly what I needed to know!  Closing issue.
